---
- hosts: webserver
  become: yes
  tasks:  
    
    - name: Install apache and dependencies
      apt: name={{ item }} update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv
        - python-mysqldb
 
    - name: starting apache service and enabling it at startup
      service: name=apache2 state=started enabled=yes
    
    - name: ensure mod_wsgi enabled
      apache2_module: name=wsgi state=present
      notify: restart apache2
    
    - name: copy contents of demo app
      copy: src=/home/vagrant/ansible/demo/app/ dest=/var/www/demo/ mode=0755
      notify: restart apache2
    
    - name: copy apache2 virtal host config
      copy: src=/home/vagrant/ansible/demo/ dest=/etc/apache2/sites-available mode=0755  
      notify: restart apache2

    - name: set-up python virtual environment
      pip: requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv
      notify: restart apache2

    - name: deactivate default apache site
      file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
      notify: restart apache2

    - name: activate demo app site
      file: src=/etc/apache2/sites-available/demo.conf dest=/etc/apache2/sites-enabled/demo.conf state=link 
      notify: restart apache2

  handlers:
    
    - name: restart apache2
      service: name=apache2 state=restarted
            

