- name: Install apache and dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: starting apache service and enabling it at startup
  service: name=apache2 state=started enabled=yes

- name: ensure mod_wsgi enabled
  apache2_module: name=wsgi state=present
  notify: restart apache2
